language: scala
scala:
- 2.11.11
jdk:
- oraclejdk8
script:
- sbt test
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
     openssl aes-256-cbc -K $encrypted_40545b9562dd_key -iv $encrypted_40545b9562dd_iv
       -in secring.gpg.enc -out secring.gpg -d;
  fi
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt
  compile publishSigned; fi
